### PR TITLE
#47 Make fits and doesNotFit consistent for matches in documents and …

### PR DESCRIPTION
**Pull request by olaf-otto**
#47

### CODE REVIEW

**Comment by DaniRey** [comment]
@olaf-otto Please review my changes. If you're ok with them, this can be merged and released as 2.0.0.
I decided to bump the major version, because this changes the behavior.

**Comment by olaf-otto** [comment]
Oh my lord I never realized there was still feedback pending :-)
Please merge!

**Comment by DaniRey** [comment]
Damn, how did we both miss that this didn't make it into 2.0.0

Now we need to rethink if we want to bump the version to 3.0.0 for this change, because it changes the behavior. But the way I plan to implement https://github.com/unic/ScalaWebTest/issues/12 would anway make a version bump necessary, therefore this should be ok.

**Comment by DaniRey** [comment]
Seems to require some additional effort before merging. The build is failing now https://travis-ci.org/unic/ScalaWebTest/builds/284274444

**Comment by DaniRey** [comment]
The changes proposed by this pull request where rebased onto a new branch and merged as part of https://github.com/unic/ScalaWebTest/pull/77

**Pull request closed without merging**
