### PR TITLE
Add access for LocalWebStorage to SeleniumChrome

### PR DESCRIPTION
**Pull request by remo-vonarx**
As discussed, here are the changes for accessing the local storage. Let me know, if I need to add/change sth.

### CODE REVIEW

**Comment by DaniRey** [comment]
Hey @remo-vonarx 

Great stuff. I would like to add this to the other browsers (Firefox and HtmlUnit) as well. 

Additionally I believe we should try to provide Local and Session Storage.

Last but not least, we have to come up with a way to test this.

**Comment by remo-vonarx** [comment]
@DaniRey fixed the tests :) Could you have another look now please?

**Comment by DaniRey** [comment]
I believe this is superseded by https://github.com/unic/ScalaWebTest/pull/119 and can be closed. Correct?

**Comment by remo-vonarx** [comment]
Sorry for the delay - yep, can be closed.

**Pull request closed without merging**
